--PREGUNTA 1

USE master
GO

CREATE DATABASE BD_PITEKSA
ON PRIMARY(
	NAME=BD_PITEKSA_PRI,
	FILENAME='C:\BD_PITEKSA\BD_PITEKSA_PRI.MDF',
	SIZE=50MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=2MB
)
LOG ON(
	NAME=BD_PITEKSA_LOG,
	FILENAME='C:\BD_PITEKSA\BD_PITEKSA_LOG.LDF',
	SIZE=10MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=2MB
)
GO

SP_HELPDB BD_PITEKSA
GO

USE BD_PITEKSA
GO

ALTER DATABASE BD_PITEKSA ADD FILEGROUP BD_PITEKSA1
ALTER DATABASE BD_PITEKSA ADD FILEGROUP BD_PITEKSA2
ALTER DATABASE BD_PITEKSA ADD FILEGROUP BD_PITEKSA3
GO

ALTER DATABASE BD_PITEKSA
ADD FILE(
	NAME=BD_PITEKSA1,
	FILENAME='C:\BD_PITEKSA\SECUNDARIOS\BD_PITEKSA1.NDF',
	SIZE=5MB,
	MAXSIZE=10MB
)TO FILEGROUP BD_PITEKSA1
GO
ALTER DATABASE BD_PITEKSA
ADD FILE(
	NAME=BD_PITEKSA2,
	FILENAME='C:\BD_PITEKSA\SECUNDARIOS\BD_PITEKSA2.NDF',
	SIZE=5MB,
	MAXSIZE=10MB
)TO FILEGROUP BD_PITEKSA2
GO
ALTER DATABASE BD_PITEKSA
ADD FILE(
	NAME=BD_PITEKSA3,
	FILENAME='C:\BD_PITEKSA\SECUNDARIOS\BD_PITEKSA3.NDF',
	SIZE=5MB,
	MAXSIZE=10MB
)TO FILEGROUP BD_PITEKSA3
GO



--PREGUNTA 2
CREATE PARTITION FUNCTION FNP_REGISTROS(INT)
AS RANGE LEFT
FOR VALUES(100,1000)
GO

CREATE PARTITION SCHEME PROYECTOS
AS PARTITION FNP_REGISTROS
TO (BD_PITEKSA1,BD_PITEKSA2,BD_PITEKSA3)
GO

CREATE TABLE RECIBO(
	numRecibo INT NOT NULL PRIMARY KEY,
	fecha DATE,
	razonSocial VARCHAR(80),
	montoTotal MONEY,
	moneda VARCHAR(50)
) ON PROYECTOS(numRecibo)
GO



--PREGUNTA 3
CREATE TABLE CLIENTE(
	IDCLIENTE CHAR(6) NOT NULL,
	CLIENTE VARCHAR(40),
	RUC CHAR(11),
	EMAIL VARCHAR(40)
)
GO

--PREGUNTA 4
SET DATEFORMAT dmy
GO

INSERT INTO RECIBO 
VALUES
(1,'02-02-2014', 'ABC.SAC', 1235.23, 'DOLARES'),
(50,'30-12-2014', 'COLINA', 12121, 'DOLARES'),
(101,'12-06-2014', 'DONOFRIO', 4545.65, 'DOLARES'),
(1001,'23-11-2014', 'SAGA', 4545.65, 'NUEVO SOLES')
GO
							
SELECT R.*, $PARTITION.FNP_REGISTROS(R.numRecibo) AS PARTICION FROM RECIBO AS R
GO


--PREGUNTA 5
CREATE CLUSTERED INDEX IDX_CLIENTE
ON CLIENTE(IDCLIENTE, CLIENTE)
GO

SELECT * FROM sys.indexes
WHERE NAME LIKE 'IDX%'

























